CREATE TABLE "DutySwapIOU" (
  "id"         TEXT NOT NULL,
  "wgId"       TEXT NOT NULL,
  "dutyId"     TEXT NOT NULL,
  "debitorId"  TEXT NOT NULL,
  "creditorId" TEXT NOT NULL,
  "redeemedAt" TIMESTAMP(3),
  "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "DutySwapIOU_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "DutySwapIOU" ADD CONSTRAINT "DutySwapIOU_wgId_fkey"
  FOREIGN KEY ("wgId") REFERENCES "WGConfig"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "DutySwapIOU" ADD CONSTRAINT "DutySwapIOU_dutyId_fkey"
  FOREIGN KEY ("dutyId") REFERENCES "Duty"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "DutySwapIOU" ADD CONSTRAINT "DutySwapIOU_debitorId_fkey"
  FOREIGN KEY ("debitorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "DutySwapIOU" ADD CONSTRAINT "DutySwapIOU_creditorId_fkey"
  FOREIGN KEY ("creditorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
